<?php
/*
 * To get this array up-to-date go to http://fortawesome.github.io/Font-Awesome/icons/
 * And execute the following script:
 * For Font-Awesome
 * <block>
 * var res = [];
 * for ( var i = 0; i < eles.length; i++ ){
 * 	var cls = eles[i].className;//.split(' ')[1];
 * 	if ( res.indexOf(cls) === -1 ){
 * 		res.push(cls);
 *     }
 * }
 * res = JSON.stringify(res, true, 4);
 * while ( res.indexOf('"') !== -1 ){
 *   res = res.replace('"', "'");
 * }
 * console.log(res);
 * document.body.innerHTML = '<pre>' + res + '</pre>';
 * </block>
 *
 * For Font-MFizz
 * <block>
 * $("div.font-mfizz-rows h4").each(function(i){
 *   r.push({txt: $(this).text(), icons: []});
 *   $(this).nextUntil("h4", "div.row").each(function(){
 *     $(".span4.font-mfizz-icon-block i", this).each(function(){
 *       var c = this.className.substr(5);
 *       if ( $.inArray(c, r) === -1 ){
 *         r[i].icons.push(c);
 *       }
 *     })
 *   })
 * });
 * $(document.body).html(JSON.stringify(r));
 * </block>
 * OR
 * <block>
 * var r = [];
 * $(".span4.font-mfizz-icon-block i").each(function(){
 *   var c = this.className.substr(5);
 *   if ( $.inArray(c, r) === -1 ){
 *     r.push(c);
 *   }
 * });
 * $(document.body).html(JSON.stringify(r));
 * </block>
 *
 */

$res = [
  'faicons' => [
    'nf nf-fa-500px',
    'nf nf-fa-accessible_icon',
    'nf nf-fa-accusoft',
    'nf nf-fa-address_book',
    'nf nf-fa-address_book',
    'nf nf-fa-address_card',
    'nf nf-fa-address_card',
    'nf nf-fa-adjust',
    'nf nf-fa-adn',
    'nf nf-fa-adversal',
    'nf nf-fa-affiliatetheme',
    'nf nf-fa-algolia',
    'nf nf-fa-align_center',
    'nf nf-fa-align_justify',
    'nf nf-fa-align_left',
    'nf nf-fa-align_right',
    'nf nf-fa-allergies',
    'nf nf-fa-amazon',
    'nf nf-fa-amazon_pay',
    'nf nf-fa-ambulance',
    'nf nf-fa-american_sign_language-interpreting',
    'nf nf-fa-amilia',
    'nf nf-fa-anchor',
    'nf nf-fa-android',
    'nf nf-fa-angellist',
    'nf nf-fa-angle_double_down',
    'nf nf-fa-angle_double_left',
    'nf nf-fa-angle_double_right',
    'nf nf-fa-angle_double_up',
    'nf nf-fa-angle_down',
    'nf nf-fa-angle_left',
    'nf nf-fa-angle_right',
    'nf nf-fa-angle_up',
    'nf nf-fa-angrycreative',
    'nf nf-fa-angular',
    'nf nf-fa-app_store',
    'nf nf-fa-app_store_ios',
    'nf nf-fa-apper',
    'nf nf-fa-apple',
    'nf nf-fa-apple_pay',
    'nf nf-fa-archive',
    'nf nf-fa-arrow_alt_circle-down',
    'nf nf-fa-arrow_alt_circle-down',
    'nf nf-fa-arrow_alt_circle-left',
    'nf nf-fa-arrow_alt_circle-left',
    'nf nf-fa-arrow_alt_circle-right',
    'nf nf-fa-arrow_alt_circle-right',
    'nf nf-fa-arrow_alt_circle-up',
    'nf nf-fa-arrow_alt_circle-up',
    'nf nf-fa-arrow_circle_down',
    'nf nf-fa-arrow_circle_left',
    'nf nf-fa-arrow_circle_right',
    'nf nf-fa-arrow_circle_up',
    'nf nf-fa-arrow_down',
    'nf nf-fa-arrow_left',
    'nf nf-fa-arrow_right',
    'nf nf-fa-arrow_up',
    'nf nf-fa-arrows_alt',
    'nf nf-fa-arrows_alt_h',
    'nf nf-fa-arrows_alt_v',
    'nf nf-fa-assistive_listening_systems',
    'nf nf-fa-asterisk',
    'nf nf-fa-asymmetrik',
    'nf nf-fa-at',
    'nf nf-fa-audible',
    'nf nf-fa-audio_description',
    'nf nf-fa-autoprefixer',
    'nf nf-fa-avianex',
    'nf nf-fa-aviato',
    'nf nf-fa-aws',
    'nf nf-fa-backward',
    'nf nf-fa-balance_scale',
    'nf nf-fa-ban',
    'nf nf-fa-band_aid',
    'nf nf-fa-bandcamp',
    'nf nf-fa-barcode',
    'nf nf-fa-bars',
    'nf nf-fa-baseball_ball',
    'nf nf-fa-basketball_ball',
    'nf nf-fa-bath',
    'nf nf-fa-battery_empty',
    'nf nf-fa-battery_full',
    'nf nf-fa-battery_half',
    'nf nf-fa-battery_quarter',
    'nf nf-fa-battery_three_quarters',
    'nf nf-fa-bed',
    'nf nf-fa-beer',
    'nf nf-fa-behance',
    'nf nf-fa-behance_square',
    'nf nf-fa-bell',
    'nf nf-fa-bell',
    'nf nf-fa-bell_slash',
    'nf nf-fa-bell_slash',
    'nf nf-fa-bicycle',
    'nf nf-fa-bimobject',
    'nf nf-fa-binoculars',
    'nf nf-fa-birthday_cake',
    'nf nf-fa-bitbucket',
    'nf nf-fa-bitcoin',
    'nf nf-fa-bity',
    'nf nf-fa-black_tie',
    'nf nf-fa-blackberry',
    'nf nf-fa-blender',
    'nf nf-fa-blind',
    'nf nf-fa-blogger',
    'nf nf-fa-blogger_b',
    'nf nf-fa-bluetooth',
    'nf nf-fa-bluetooth_b',
    'nf nf-fa-bold',
    'nf nf-fa-bolt',
    'nf nf-fa-bomb',
    'nf nf-fa-book',
    'nf nf-fa-book_open',
    'nf nf-fa-bookmark',
    'nf nf-fa-bookmark',
    'nf nf-fa-bowling_ball',
    'nf nf-fa-box',
    'nf nf-fa-box_open',
    'nf nf-fa-boxes',
    'nf nf-fa-braille',
    'nf nf-fa-briefcase',
    'nf nf-fa-briefcase_medical',
    'nf nf-fa-broadcast_tower',
    'nf nf-fa-broom',
    'nf nf-fa-btc',
    'nf nf-fa-bug',
    'nf nf-fa-building',
    'nf nf-fa-building',
    'nf nf-fa-bullhorn',
    'nf nf-fa-bullseye',
    'nf nf-fa-burn',
    'nf nf-fa-buromobelexperte',
    'nf nf-fa-bus',
    'nf nf-fa-buysellads',
    'nf nf-fa-calculator',
    'nf nf-fa-calendar',
    'nf nf-fa-calendar',
    'nf nf-fa-calendar_alt',
    'nf nf-fa-calendar_alt',
    'nf nf-fa-calendar_check',
    'nf nf-fa-calendar_check',
    'nf nf-fa-calendar_minus',
    'nf nf-fa-calendar_minus',
    'nf nf-fa-calendar_plus',
    'nf nf-fa-calendar_plus',
    'nf nf-fa-calendar_times',
    'nf nf-fa-calendar_times',
    'nf nf-fa-camera',
    'nf nf-fa-camera_retro',
    'nf nf-fa-capsules',
    'nf nf-fa-car',
    'nf nf-fa-caret_down',
    'nf nf-fa-caret_left',
    'nf nf-fa-caret_right',
    'nf nf-fa-caret_square_down',
    'nf nf-fa-caret_square_down',
    'nf nf-fa-caret_square_left',
    'nf nf-fa-caret_square_left',
    'nf nf-fa-caret_square_right',
    'nf nf-fa-caret_square_right',
    'nf nf-fa-caret_square_up',
    'nf nf-fa-caret_square_up',
    'nf nf-fa-caret_up',
    'nf nf-fa-cart_arrow_down',
    'nf nf-fa-cart_plus',
    'nf nf-fa-cc_amazon_pay',
    'nf nf-fa-cc_amex',
    'nf nf-fa-cc_apple_pay',
    'nf nf-fa-cc_diners_club',
    'nf nf-fa-cc_discover',
    'nf nf-fa-cc_jcb',
    'nf nf-fa-cc_mastercard',
    'nf nf-fa-cc_paypal',
    'nf nf-fa-cc_stripe',
    'nf nf-fa-cc_visa',
    'nf nf-fa-centercode',
    'nf nf-fa-certificate',
    'nf nf-fa-chalkboard',
    'nf nf-fa-chalkboard_teacher',
    'nf nf-fa-chart_area',
    'nf nf-fa-chart_bar',
    'nf nf-fa-chart_bar',
    'nf nf-fa-chart_line',
    'nf nf-fa-chart_pie',
    'nf nf-fa-check',
    'nf nf-fa-check_circle',
    'nf nf-fa-check_circle',
    'nf nf-fa-check_square',
    'nf nf-fa-check_square',
    'nf nf-fa-chess',
    'nf nf-fa-chess_bishop',
    'nf nf-fa-chess_board',
    'nf nf-fa-chess_king',
    'nf nf-fa-chess_knight',
    'nf nf-fa-chess_pawn',
    'nf nf-fa-chess_queen',
    'nf nf-fa-chess_rook',
    'nf nf-fa-chevron_circle_down',
    'nf nf-fa-chevron_circle_left',
    'nf nf-fa-chevron_circle_right',
    'nf nf-fa-chevron_circle_up',
    'nf nf-fa-chevron_down',
    'nf nf-fa-chevron_left',
    'nf nf-fa-chevron_right',
    'nf nf-fa-chevron_up',
    'nf nf-fa-child',
    'nf nf-fa-chrome',
    'nf nf-fa-church',
    'nf nf-fa-circle',
    'nf nf-fa-circle',
    'nf nf-fa-circle_notch',
    'nf nf-fa-clipboard',
    'nf nf-fa-clipboard',
    'nf nf-fa-clipboard_check',
    'nf nf-fa-clipboard_list',
    'nf nf-fa-clock',
    'nf nf-fa-clock',
    'nf nf-fa-clone',
    'nf nf-fa-clone',
    'nf nf-fa-closed_captioning',
    'nf nf-fa-closed_captioning',
    'nf nf-fa-cloud',
    'nf nf-fa-cloud_download_alt',
    'nf nf-fa-cloud_upload_alt',
    'nf nf-fa-cloudscale',
    'nf nf-fa-cloudsmith',
    'nf nf-fa-cloudversify',
    'nf nf-fa-code',
    'nf nf-fa-code_branch',
    'nf nf-fa-codepen',
    'nf nf-fa-codiepie',
    'nf nf-fa-coffee',
    'nf nf-fa-cog',
    'nf nf-fa-cogs',
    'nf nf-fa-coins',
    'nf nf-fa-columns',
    'nf nf-fa-comment',
    'nf nf-fa-comment',
    'nf nf-fa-comment_alt',
    'nf nf-fa-comment_alt',
    'nf nf-fa-comment_dots',
    'nf nf-fa-comment_dots',
    'nf nf-fa-comment_slash',
    'nf nf-fa-comments',
    'nf nf-fa-comments',
    'nf nf-fa-compact_disc',
    'nf nf-fa-compass',
    'nf nf-fa-compass',
    'nf nf-fa-compress',
    'nf nf-fa-connectdevelop',
    'nf nf-fa-contao',
    'nf nf-fa-copy',
    'nf nf-fa-copy',
    'nf nf-fa-copyright',
    'nf nf-fa-copyright',
    'nf nf-fa-couch',
    'nf nf-fa-cpanel',
    'nf nf-fa-creative_commons',
    'nf nf-fa-creative_commons_by',
    'nf nf-fa-creative_commons_nc',
    'nf nf-fa-creative_commons_nc-eu',
    'nf nf-fa-creative_commons_nc-jp',
    'nf nf-fa-creative_commons_nd',
    'nf nf-fa-creative_commons_pd',
    'nf nf-fa-creative_commons_pd-alt',
    'nf nf-fa-creative_commons_remix',
    'nf nf-fa-creative_commons_sa',
    'nf nf-fa-creative_commons_sampling',
    'nf nf-fa-creative_commons_sampling-plus',
    'nf nf-fa-creative_commons_share',
    'nf nf-fa-credit_card',
    'nf nf-fa-credit_card',
    'nf nf-fa-crop',
    'nf nf-fa-crosshairs',
    'nf nf-fa-crow',
    'nf nf-fa-crown',
    'nf nf-fa-css3',
    'nf nf-fa-css3-alt',
    'nf nf-fa-cube',
    'nf nf-fa-cubes',
    'nf nf-fa-cut',
    'nf nf-fa-cuttlefish',
    'nf nf-fa-d_and_d',
    'nf nf-fa-dashcube',
    'nf nf-fa-database',
    'nf nf-fa-deaf',
    'nf nf-fa-delicious',
    'nf nf-fa-deploydog',
    'nf nf-fa-deskpro',
    'nf nf-fa-desktop',
    'nf nf-fa-deviantart',
    'nf nf-fa-diagnoses',
    'nf nf-fa-dice',
    'nf nf-fa-dice_five',
    'nf nf-fa-dice_four',
    'nf nf-fa-dice_one',
    'nf nf-fa-dice_six',
    'nf nf-fa-dice_three',
    'nf nf-fa-dice_two',
    'nf nf-fa-digg',
    'nf nf-fa-digital_ocean',
    'nf nf-fa-discord',
    'nf nf-fa-discourse',
    'nf nf-fa-divide',
    'nf nf-fa-dna',
    'nf nf-fa-dochub',
    'nf nf-fa-docker',
    'nf nf-fa-dollar_sign',
    'nf nf-fa-dolly',
    'nf nf-fa-dolly_flatbed',
    'nf nf-fa-donate',
    'nf nf-fa-door_closed',
    'nf nf-fa-door_open',
    'nf nf-fa-dot_circle',
    'nf nf-fa-dot_circle',
    'nf nf-fa-dove',
    'nf nf-fa-download',
    'nf nf-fa-draft2digital',
    'nf nf-fa-dribbble',
    'nf nf-fa-dribbble_square',
    'nf nf-fa-dropbox',
    'nf nf-fa-drupal',
    'nf nf-fa-dumbbell',
    'nf nf-fa-dyalog',
    'nf nf-fa-earlybirds',
    'nf nf-fa-ebay',
    'nf nf-fa-edge',
    'nf nf-fa-edit',
    'nf nf-fa-edit',
    'nf nf-fa-eject',
    'nf nf-fa-elementor',
    'nf nf-fa-ellipsis_h',
    'nf nf-fa-ellipsis_v',
    'nf nf-fa-ember',
    'nf nf-fa-empire',
    'nf nf-fa-envelope',
    'nf nf-fa-envelope',
    'nf nf-fa-envelope_open',
    'nf nf-fa-envelope_open',
    'nf nf-fa-envelope_square',
    'nf nf-fa-envira',
    'nf nf-fa-equals',
    'nf nf-fa-eraser',
    'nf nf-fa-erlang',
    'nf nf-fa-ethereum',
    'nf nf-fa-etsy',
    'nf nf-fa-euro_sign',
    'nf nf-fa-exchange_alt',
    'nf nf-fa-exclamation',
    'nf nf-fa-exclamation_circle',
    'nf nf-fa-exclamation_triangle',
    'nf nf-fa-expand',
    'nf nf-fa-expand_arrows_alt',
    'nf nf-fa-expeditedssl',
    'nf nf-fa-external_link_alt',
    'nf nf-fa-external_link_square-alt',
    'nf nf-fa-eye',
    'nf nf-fa-eye',
    'nf nf-fa-eye_dropper',
    'nf nf-fa-eye_slash',
    'nf nf-fa-eye_slash',
    'nf nf-fa-facebook',
    'nf nf-fa-facebook_f',
    'nf nf-fa-facebook_messenger',
    'nf nf-fa-facebook_square',
    'nf nf-fa-fast_backward',
    'nf nf-fa-fast_forward',
    'nf nf-fa-fax',
    'nf nf-fa-feather',
    'nf nf-fa-female',
    'nf nf-fa-fighter_jet',
    'nf nf-fa-file',
    'nf nf-fa-file',
    'nf nf-fa-file_alt',
    'nf nf-fa-file_alt',
    'nf nf-fa-file_archive',
    'nf nf-fa-file_archive',
    'nf nf-fa-file_audio',
    'nf nf-fa-file_audio',
    'nf nf-fa-file_code',
    'nf nf-fa-file_code',
    'nf nf-fa-file_excel',
    'nf nf-fa-file_excel',
    'nf nf-fa-file_image',
    'nf nf-fa-file_image',
    'nf nf-fa-file_medical',
    'nf nf-fa-file_medical_alt',
    'nf nf-fa-file_pdf',
    'nf nf-fa-file_pdf',
    'nf nf-fa-file_powerpoint',
    'nf nf-fa-file_powerpoint',
    'nf nf-fa-file_video',
    'nf nf-fa-file_video',
    'nf nf-fa-file_word',
    'nf nf-fa-file_word',
    'nf nf-fa-film',
    'nf nf-fa-filter',
    'nf nf-fa-fire',
    'nf nf-fa-fire_extinguisher',
    'nf nf-fa-firefox',
    'nf nf-fa-first_aid',
    'nf nf-fa-first_order',
    'nf nf-fa-first_order_alt',
    'nf nf-fa-firstdraft',
    'nf nf-fa-flag',
    'nf nf-fa-flag',
    'nf nf-fa-flag_checkered',
    'nf nf-fa-flask',
    'nf nf-fa-flickr',
    'nf nf-fa-flipboard',
    'nf nf-fa-fly',
    'nf nf-fa-folder',
    'nf nf-fa-folder',
    'nf nf-fa-folder_open',
    'nf nf-fa-folder_open',
    'nf nf-fa-font',
    'nf nf-fa-font_awesome',
    'nf nf-fa-font_awesome_alt',
    'nf nf-fa-font_awesome_flag',
    'nf nf-fa-font_awesome_logo-full',
    'nf nf-fa-font_awesome_logo-full',
    'nf nf-fa-font_awesome_logo-full',
    'nf nf-fa-fonticons',
    'nf nf-fa-fonticons_fi',
    'nf nf-fa-football_ball',
    'nf nf-fa-fort_awesome',
    'nf nf-fa-fort_awesome_alt',
    'nf nf-fa-forumbee',
    'nf nf-fa-forward',
    'nf nf-fa-foursquare',
    'nf nf-fa-free_code_camp',
    'nf nf-fa-freebsd',
    'nf nf-fa-frog',
    'nf nf-fa-frown',
    'nf nf-fa-frown',
    'nf nf-fa-fulcrum',
    'nf nf-fa-futbol',
    'nf nf-fa-futbol',
    'nf nf-fa-galactic_republic',
    'nf nf-fa-galactic_senate',
    'nf nf-fa-gamepad',
    'nf nf-fa-gas_pump',
    'nf nf-fa-gavel',
    'nf nf-fa-gem',
    'nf nf-fa-gem',
    'nf nf-fa-genderless',
    'nf nf-fa-get_pocket',
    'nf nf-fa-gg',
    'nf nf-fa-gg_circle',
    'nf nf-fa-gift',
    'nf nf-fa-git',
    'nf nf-fa-git_square',
    'nf nf-fa-github',
    'nf nf-fa-github_alt',
    'nf nf-fa-github_square',
    'nf nf-fa-gitkraken',
    'nf nf-fa-gitlab',
    'nf nf-fa-gitter',
    'nf nf-fa-glass_martini',
    'nf nf-fa-glasses',
    'nf nf-fa-glide',
    'nf nf-fa-glide_g',
    'nf nf-fa-globe',
    'nf nf-fa-gofore',
    'nf nf-fa-golf_ball',
    'nf nf-fa-goodreads',
    'nf nf-fa-goodreads_g',
    'nf nf-fa-google',
    'nf nf-fa-google_drive',
    'nf nf-fa-google_play',
    'nf nf-fa-google_plus',
    'nf nf-fa-google_plus_g',
    'nf nf-fa-google_plus_square',
    'nf nf-fa-google_wallet',
    'nf nf-fa-graduation_cap',
    'nf nf-fa-gratipay',
    'nf nf-fa-grav',
    'nf nf-fa-greater_than',
    'nf nf-fa-greater_than_equal',
    'nf nf-fa-gripfire',
    'nf nf-fa-grunt',
    'nf nf-fa-gulp',
    'nf nf-fa-h_square',
    'nf nf-fa-hacker_news',
    'nf nf-fa-hacker_news_square',
    'nf nf-fa-hand_holding',
    'nf nf-fa-hand_holding_heart',
    'nf nf-fa-hand_holding_usd',
    'nf nf-fa-hand_lizard',
    'nf nf-fa-hand_lizard',
    'nf nf-fa-hand_paper',
    'nf nf-fa-hand_paper',
    'nf nf-fa-hand_peace',
    'nf nf-fa-hand_peace',
    'nf nf-fa-hand_point_down',
    'nf nf-fa-hand_point_down',
    'nf nf-fa-hand_point_left',
    'nf nf-fa-hand_point_left',
    'nf nf-fa-hand_point_right',
    'nf nf-fa-hand_point_right',
    'nf nf-fa-hand_point_up',
    'nf nf-fa-hand_point_up',
    'nf nf-fa-hand_pointer',
    'nf nf-fa-hand_pointer',
    'nf nf-fa-hand_rock',
    'nf nf-fa-hand_rock',
    'nf nf-fa-hand_scissors',
    'nf nf-fa-hand_scissors',
    'nf nf-fa-hand_spock',
    'nf nf-fa-hand_spock',
    'nf nf-fa-hands',
    'nf nf-fa-hands_helping',
    'nf nf-fa-handshake',
    'nf nf-fa-handshake',
    'nf nf-fa-hashtag',
    'nf nf-fa-hdd',
    'nf nf-fa-hdd',
    'nf nf-fa-heading',
    'nf nf-fa-headphones',
    'nf nf-fa-heart',
    'nf nf-fa-heart',
    'nf nf-fa-heartbeat',
    'nf nf-fa-helicopter',
    'nf nf-fa-hips',
    'nf nf-fa-hire_a_helper',
    'nf nf-fa-history',
    'nf nf-fa-hockey_puck',
    'nf nf-fa-home',
    'nf nf-fa-hooli',
    'nf nf-fa-hospital',
    'nf nf-fa-hospital',
    'nf nf-fa-hospital_alt',
    'nf nf-fa-hospital_symbol',
    'nf nf-fa-hotjar',
    'nf nf-fa-hourglass',
    'nf nf-fa-hourglass',
    'nf nf-fa-hourglass_end',
    'nf nf-fa-hourglass_half',
    'nf nf-fa-hourglass_start',
    'nf nf-fa-houzz',
    'nf nf-fa-html5',
    'nf nf-fa-hubspot',
    'nf nf-fa-i_cursor',
    'nf nf-fa-id_badge',
    'nf nf-fa-id_badge',
    'nf nf-fa-id_card',
    'nf nf-fa-id_card',
    'nf nf-fa-id_card_alt',
    'nf nf-fa-image',
    'nf nf-fa-image',
    'nf nf-fa-images',
    'nf nf-fa-images',
    'nf nf-fa-imdb',
    'nf nf-fa-inbox',
    'nf nf-fa-indent',
    'nf nf-fa-industry',
    'nf nf-fa-infinity',
    'nf nf-fa-info',
    'nf nf-fa-info_circle',
    'nf nf-fa-instagram',
    'nf nf-fa-internet_explorer',
    'nf nf-fa-ioxhost',
    'nf nf-fa-italic',
    'nf nf-fa-itunes',
    'nf nf-fa-itunes_note',
    'nf nf-fa-java',
    'nf nf-fa-jedi_order',
    'nf nf-fa-jenkins',
    'nf nf-fa-joget',
    'nf nf-fa-joomla',
    'nf nf-fa-js',
    'nf nf-fa-js_square',
    'nf nf-fa-jsfiddle',
    'nf nf-fa-key',
    'nf nf-fa-keybase',
    'nf nf-fa-keyboard',
    'nf nf-fa-keyboard',
    'nf nf-fa-keycdn',
    'nf nf-fa-kickstarter',
    'nf nf-fa-kickstarter_k',
    'nf nf-fa-kiwi_bird',
    'nf nf-fa-korvue',
    'nf nf-fa-language',
    'nf nf-fa-laptop',
    'nf nf-fa-laravel',
    'nf nf-fa-lastfm',
    'nf nf-fa-lastfm_square',
    'nf nf-fa-leaf',
    'nf nf-fa-leanpub',
    'nf nf-fa-lemon',
    'nf nf-fa-lemon',
    'nf nf-fa-less',
    'nf nf-fa-less_than',
    'nf nf-fa-less_than_equal',
    'nf nf-fa-level_down_alt',
    'nf nf-fa-level_up_alt',
    'nf nf-fa-life_ring',
    'nf nf-fa-life_ring',
    'nf nf-fa-lightbulb',
    'nf nf-fa-lightbulb',
    'nf nf-fa-line',
    'nf nf-fa-link',
    'nf nf-fa-linkedin',
    'nf nf-fa-linkedin_in',
    'nf nf-fa-linode',
    'nf nf-fa-linux',
    'nf nf-fa-lira_sign',
    'nf nf-fa-list',
    'nf nf-fa-list_alt',
    'nf nf-fa-list_alt',
    'nf nf-fa-list_ol',
    'nf nf-fa-list_ul',
    'nf nf-fa-location_arrow',
    'nf nf-fa-lock',
    'nf nf-fa-lock_open',
    'nf nf-fa-long_arrow_alt-down',
    'nf nf-fa-long_arrow_alt-left',
    'nf nf-fa-long_arrow_alt-right',
    'nf nf-fa-long_arrow_alt-up',
    'nf nf-fa-low_vision',
    'nf nf-fa-lyft',
    'nf nf-fa-magento',
    'nf nf-fa-magic',
    'nf nf-fa-magnet',
    'nf nf-fa-male',
    'nf nf-fa-mandalorian',
    'nf nf-fa-map',
    'nf nf-fa-map',
    'nf nf-fa-map_marker',
    'nf nf-fa-map_marker_alt',
    'nf nf-fa-map_pin',
    'nf nf-fa-map_signs',
    'nf nf-fa-mars',
    'nf nf-fa-mars_double',
    'nf nf-fa-mars_stroke',
    'nf nf-fa-mars_stroke_h',
    'nf nf-fa-mars_stroke_v',
    'nf nf-fa-mastodon',
    'nf nf-fa-maxcdn',
    'nf nf-fa-medapps',
    'nf nf-fa-medium',
    'nf nf-fa-medium_m',
    'nf nf-fa-medkit',
    'nf nf-fa-medrt',
    'nf nf-fa-meetup',
    'nf nf-fa-meh',
    'nf nf-fa-meh',
    'nf nf-fa-memory',
    'nf nf-fa-mercury',
    'nf nf-fa-microchip',
    'nf nf-fa-microphone',
    'nf nf-fa-microphone_alt',
    'nf nf-fa-microphone_alt_slash',
    'nf nf-fa-microphone_slash',
    'nf nf-fa-microsoft',
    'nf nf-fa-minus',
    'nf nf-fa-minus_circle',
    'nf nf-fa-minus_square',
    'nf nf-fa-minus_square',
    'nf nf-fa-mix',
    'nf nf-fa-mixcloud',
    'nf nf-fa-mizuni',
    'nf nf-fa-mobile',
    'nf nf-fa-mobile_alt',
    'nf nf-fa-modx',
    'nf nf-fa-monero',
    'nf nf-fa-money_bill',
    'nf nf-fa-money_bill_alt',
    'nf nf-fa-money_bill_alt',
    'nf nf-fa-money_bill_wave',
    'nf nf-fa-money_bill_wave-alt',
    'nf nf-fa-money_check',
    'nf nf-fa-money_check_alt',
    'nf nf-fa-moon',
    'nf nf-fa-moon',
    'nf nf-fa-motorcycle',
    'nf nf-fa-mouse_pointer',
    'nf nf-fa-music',
    'nf nf-fa-napster',
    'nf nf-fa-neuter',
    'nf nf-fa-newspaper',
    'nf nf-fa-newspaper',
    'nf nf-fa-nintendo_switch',
    'nf nf-fa-node',
    'nf nf-fa-node_js',
    'nf nf-fa-not_equal',
    'nf nf-fa-notes_medical',
    'nf nf-fa-npm',
    'nf nf-fa-ns8',
    'nf nf-fa-nutritionix',
    'nf nf-fa-object_group',
    'nf nf-fa-object_group',
    'nf nf-fa-object_ungroup',
    'nf nf-fa-object_ungroup',
    'nf nf-fa-odnoklassniki',
    'nf nf-fa-odnoklassniki_square',
    'nf nf-fa-old_republic',
    'nf nf-fa-opencart',
    'nf nf-fa-openid',
    'nf nf-fa-opera',
    'nf nf-fa-optin_monster',
    'nf nf-fa-osi',
    'nf nf-fa-outdent',
    'nf nf-fa-page4',
    'nf nf-fa-pagelines',
    'nf nf-fa-paint_brush',
    'nf nf-fa-palette',
    'nf nf-fa-palfed',
    'nf nf-fa-pallet',
    'nf nf-fa-paper_plane',
    'nf nf-fa-paper_plane',
    'nf nf-fa-paperclip',
    'nf nf-fa-parachute_box',
    'nf nf-fa-paragraph',
    'nf nf-fa-parking',
    'nf nf-fa-paste',
    'nf nf-fa-patreon',
    'nf nf-fa-pause',
    'nf nf-fa-pause_circle',
    'nf nf-fa-pause_circle',
    'nf nf-fa-paw',
    'nf nf-fa-paypal',
    'nf nf-fa-pen_square',
    'nf nf-fa-pencil_alt',
    'nf nf-fa-people_carry',
    'nf nf-fa-percent',
    'nf nf-fa-percentage',
    'nf nf-fa-periscope',
    'nf nf-fa-phabricator',
    'nf nf-fa-phoenix_framework',
    'nf nf-fa-phoenix_squadron',
    'nf nf-fa-phone',
    'nf nf-fa-phone_slash',
    'nf nf-fa-phone_square',
    'nf nf-fa-phone_volume',
    'nf nf-fa-php',
    'nf nf-fa-pied_piper',
    'nf nf-fa-pied_piper_alt',
    'nf nf-fa-pied_piper_hat',
    'nf nf-fa-pied_piper_pp',
    'nf nf-fa-piggy_bank',
    'nf nf-fa-pills',
    'nf nf-fa-pinterest',
    'nf nf-fa-pinterest_p',
    'nf nf-fa-pinterest_square',
    'nf nf-fa-plane',
    'nf nf-fa-play',
    'nf nf-fa-play_circle',
    'nf nf-fa-play_circle',
    'nf nf-fa-playstation',
    'nf nf-fa-plug',
    'nf nf-fa-plus',
    'nf nf-fa-plus_circle',
    'nf nf-fa-plus_square',
    'nf nf-fa-plus_square',
    'nf nf-fa-podcast',
    'nf nf-fa-poo',
    'nf nf-fa-portrait',
    'nf nf-fa-pound_sign',
    'nf nf-fa-power_off',
    'nf nf-fa-prescription_bottle',
    'nf nf-fa-prescription_bottle_alt',
    'nf nf-fa-print',
    'nf nf-fa-procedures',
    'nf nf-fa-product_hunt',
    'nf nf-fa-project_diagram',
    'nf nf-fa-pushed',
    'nf nf-fa-puzzle_piece',
    'nf nf-fa-python',
    'nf nf-fa-qq',
    'nf nf-fa-qrcode',
    'nf nf-fa-question',
    'nf nf-fa-question_circle',
    'nf nf-fa-question_circle',
    'nf nf-fa-quidditch',
    'nf nf-fa-quinscape',
    'nf nf-fa-quora',
    'nf nf-fa-quote_left',
    'nf nf-fa-quote_right',
    'nf nf-fa-r_project',
    'nf nf-fa-random',
    'nf nf-fa-ravelry',
    'nf nf-fa-react',
    'nf nf-fa-readme',
    'nf nf-fa-rebel',
    'nf nf-fa-receipt',
    'nf nf-fa-recycle',
    'nf nf-fa-red_river',
    'nf nf-fa-reddit',
    'nf nf-fa-reddit_alien',
    'nf nf-fa-reddit_square',
    'nf nf-fa-redo',
    'nf nf-fa-redo_alt',
    'nf nf-fa-registered',
    'nf nf-fa-registered',
    'nf nf-fa-rendact',
    'nf nf-fa-renren',
    'nf nf-fa-reply',
    'nf nf-fa-reply_all',
    'nf nf-fa-replyd',
    'nf nf-fa-researchgate',
    'nf nf-fa-resolving',
    'nf nf-fa-retweet',
    'nf nf-fa-ribbon',
    'nf nf-fa-road',
    'nf nf-fa-robot',
    'nf nf-fa-rocket',
    'nf nf-fa-rocketchat',
    'nf nf-fa-rockrms',
    'nf nf-fa-rss',
    'nf nf-fa-rss_square',
    'nf nf-fa-ruble_sign',
    'nf nf-fa-ruler',
    'nf nf-fa-ruler_combined',
    'nf nf-fa-ruler_horizontal',
    'nf nf-fa-ruler_vertical',
    'nf nf-fa-rupee_sign',
    'nf nf-fa-safari',
    'nf nf-fa-sass',
    'nf nf-fa-save',
    'nf nf-fa-save',
    'nf nf-fa-schlix',
    'nf nf-fa-school',
    'nf nf-fa-screwdriver',
    'nf nf-fa-scribd',
    'nf nf-fa-search',
    'nf nf-fa-search_minus',
    'nf nf-fa-search_plus',
    'nf nf-fa-searchengin',
    'nf nf-fa-seedling',
    'nf nf-fa-sellcast',
    'nf nf-fa-sellsy',
    'nf nf-fa-server',
    'nf nf-fa-servicestack',
    'nf nf-fa-share',
    'nf nf-fa-share_alt',
    'nf nf-fa-share_alt_square',
    'nf nf-fa-share_square',
    'nf nf-fa-share_square',
    'nf nf-fa-shekel_sign',
    'nf nf-fa-shield_alt',
    'nf nf-fa-ship',
    'nf nf-fa-shipping_fast',
    'nf nf-fa-shirtsinbulk',
    'nf nf-fa-shoe_prints',
    'nf nf-fa-shopping_bag',
    'nf nf-fa-shopping_basket',
    'nf nf-fa-shopping_cart',
    'nf nf-fa-shower',
    'nf nf-fa-sign',
    'nf nf-fa-sign_in_alt',
    'nf nf-fa-sign_language',
    'nf nf-fa-sign_out_alt',
    'nf nf-fa-signal',
    'nf nf-fa-simplybuilt',
    'nf nf-fa-sistrix',
    'nf nf-fa-sitemap',
    'nf nf-fa-sith',
    'nf nf-fa-skull',
    'nf nf-fa-skyatlas',
    'nf nf-fa-skype',
    'nf nf-fa-slack',
    'nf nf-fa-slack_hash',
    'nf nf-fa-sliders_h',
    'nf nf-fa-slideshare',
    'nf nf-fa-smile',
    'nf nf-fa-smile',
    'nf nf-fa-smoking',
    'nf nf-fa-smoking_ban',
    'nf nf-fa-snapchat',
    'nf nf-fa-snapchat_ghost',
    'nf nf-fa-snapchat_square',
    'nf nf-fa-snowflake',
    'nf nf-fa-snowflake',
    'nf nf-fa-sort',
    'nf nf-fa-sort_alpha_down',
    'nf nf-fa-sort_alpha_up',
    'nf nf-fa-sort_amount_down',
    'nf nf-fa-sort_amount_up',
    'nf nf-fa-sort_down',
    'nf nf-fa-sort_numeric_down',
    'nf nf-fa-sort_numeric_up',
    'nf nf-fa-sort_up',
    'nf nf-fa-soundcloud',
    'nf nf-fa-space_shuttle',
    'nf nf-fa-speakap',
    'nf nf-fa-spinner',
    'nf nf-fa-spotify',
    'nf nf-fa-square',
    'nf nf-fa-square',
    'nf nf-fa-square_full',
    'nf nf-fa-stack_exchange',
    'nf nf-fa-stack_overflow',
    'nf nf-fa-star',
    'nf nf-fa-star',
    'nf nf-fa-star_half',
    'nf nf-fa-star_half',
    'nf nf-fa-staylinked',
    'nf nf-fa-steam',
    'nf nf-fa-steam_square',
    'nf nf-fa-steam_symbol',
    'nf nf-fa-step_backward',
    'nf nf-fa-step_forward',
    'nf nf-fa-stethoscope',
    'nf nf-fa-sticker_mule',
    'nf nf-fa-sticky_note',
    'nf nf-fa-sticky_note',
    'nf nf-fa-stop',
    'nf nf-fa-stop_circle',
    'nf nf-fa-stop_circle',
    'nf nf-fa-stopwatch',
    'nf nf-fa-store',
    'nf nf-fa-store_alt',
    'nf nf-fa-strava',
    'nf nf-fa-stream',
    'nf nf-fa-street_view',
    'nf nf-fa-strikethrough',
    'nf nf-fa-stripe',
    'nf nf-fa-stripe_s',
    'nf nf-fa-stroopwafel',
    'nf nf-fa-studiovinari',
    'nf nf-fa-stumbleupon',
    'nf nf-fa-stumbleupon_circle',
    'nf nf-fa-subscript',
    'nf nf-fa-subway',
    'nf nf-fa-suitcase',
    'nf nf-fa-sun',
    'nf nf-fa-sun',
    'nf nf-fa-superpowers',
    'nf nf-fa-superscript',
    'nf nf-fa-supple',
    'nf nf-fa-sync',
    'nf nf-fa-sync_alt',
    'nf nf-fa-syringe',
    'nf nf-fa-table',
    'nf nf-fa-table_tennis',
    'nf nf-fa-tablet',
    'nf nf-fa-tablet_alt',
    'nf nf-fa-tablets',
    'nf nf-fa-tachometer_alt',
    'nf nf-fa-tag',
    'nf nf-fa-tags',
    'nf nf-fa-tape',
    'nf nf-fa-tasks',
    'nf nf-fa-taxi',
    'nf nf-fa-teamspeak',
    'nf nf-fa-telegram',
    'nf nf-fa-telegram_plane',
    'nf nf-fa-tencent_weibo',
    'nf nf-fa-terminal',
    'nf nf-fa-text_height',
    'nf nf-fa-text_width',
    'nf nf-fa-th',
    'nf nf-fa-th_large',
    'nf nf-fa-th_list',
    'nf nf-fa-themeisle',
    'nf nf-fa-thermometer',
    'nf nf-fa-thermometer_empty',
    'nf nf-fa-thermometer_full',
    'nf nf-fa-thermometer_half',
    'nf nf-fa-thermometer_quarter',
    'nf nf-fa-thermometer_three_quarters',
    'nf nf-fa-thumbs_down',
    'nf nf-fa-thumbs_down',
    'nf nf-fa-thumbs_up',
    'nf nf-fa-thumbs_up',
    'nf nf-fa-thumbtack',
    'nf nf-fa-ticket_alt',
    'nf nf-fa-times',
    'nf nf-fa-times_circle',
    'nf nf-fa-times_circle',
    'nf nf-fa-tint',
    'nf nf-fa-toggle_off',
    'nf nf-fa-toggle_on',
    'nf nf-fa-toolbox',
    'nf nf-fa-trade_federation',
    'nf nf-fa-trademark',
    'nf nf-fa-train',
    'nf nf-fa-transgender',
    'nf nf-fa-transgender_alt',
    'nf nf-fa-trash',
    'nf nf-fa-trash_alt',
    'nf nf-fa-trash_alt_alt',
    'nf nf-fa-tree',
    'nf nf-fa-trello',
    'nf nf-fa-tripadvisor',
    'nf nf-fa-trophy',
    'nf nf-fa-truck',
    'nf nf-fa-truck_loading',
    'nf nf-fa-truck_moving',
    'nf nf-fa-tshirt',
    'nf nf-fa-tty',
    'nf nf-fa-tumblr',
    'nf nf-fa-tumblr_square',
    'nf nf-fa-tv',
    'nf nf-fa-twitch',
    'nf nf-fa-twitter',
    'nf nf-fa-twitter_square',
    'nf nf-fa-typo3',
    'nf nf-fa-uber',
    'nf nf-fa-uikit',
    'nf nf-fa-umbrella',
    'nf nf-fa-underline',
    'nf nf-fa-undo',
    'nf nf-fa-undo_alt',
    'nf nf-fa-uniregistry',
    'nf nf-fa-universal_access',
    'nf nf-fa-university',
    'nf nf-fa-unlink',
    'nf nf-fa-unlock',
    'nf nf-fa-unlock_alt',
    'nf nf-fa-untappd',
    'nf nf-fa-upload',
    'nf nf-fa-usb',
    'nf nf-fa-user',
    'nf nf-fa-user',
    'nf nf-fa-user_alt',
    'nf nf-fa-user_alt_slash',
    'nf nf-fa-user_astronaut',
    'nf nf-fa-user_check',
    'nf nf-fa-user_circle',
    'nf nf-fa-user_circle',
    'nf nf-fa-user_clock',
    'nf nf-fa-user_cog',
    'nf nf-fa-user_edit',
    'nf nf-fa-user_friends',
    'nf nf-fa-user_graduate',
    'nf nf-fa-user_lock',
    'nf nf-fa-user_md',
    'nf nf-fa-user_minus',
    'nf nf-fa-user_ninja',
    'nf nf-fa-user_plus',
    'nf nf-fa-user_secret',
    'nf nf-fa-user_shield',
    'nf nf-fa-user_slash',
    'nf nf-fa-user_tag',
    'nf nf-fa-user_tie',
    'nf nf-fa-user_times',
    'nf nf-fa-users',
    'nf nf-fa-users_cog',
    'nf nf-fa-ussunnah',
    'nf nf-fa-utensil_spoon',
    'nf nf-fa-utensils',
    'nf nf-fa-vaadin',
    'nf nf-fa-venus',
    'nf nf-fa-venus_double',
    'nf nf-fa-venus_mars',
    'nf nf-fa-viacoin',
    'nf nf-fa-viadeo',
    'nf nf-fa-viadeo_square',
    'nf nf-fa-vial',
    'nf nf-fa-vials',
    'nf nf-fa-viber',
    'nf nf-fa-video',
    'nf nf-fa-video_slash',
    'nf nf-fa-vimeo',
    'nf nf-fa-vimeo_square',
    'nf nf-fa-vimeo_v',
    'nf nf-fa-vine',
    'nf nf-fa-vk',
    'nf nf-fa-vnv',
    'nf nf-fa-volleyball_ball',
    'nf nf-fa-volume_down',
    'nf nf-fa-volume_off',
    'nf nf-fa-volume_up',
    'nf nf-fa-vuejs',
    'nf nf-fa-walking',
    'nf nf-fa-wallet',
    'nf nf-fa-warehouse',
    'nf nf-fa-weibo',
    'nf nf-fa-weight',
    'nf nf-fa-weixin',
    'nf nf-fa-whatsapp',
    'nf nf-fa-whatsapp_square',
    'nf nf-fa-wheelchair',
    'nf nf-fa-whmcs',
    'nf nf-fa-wifi',
    'nf nf-fa-wikipedia_w',
    'nf nf-fa-window_close',
    'nf nf-fa-window_close',
    'nf nf-fa-window_maximize',
    'nf nf-fa-window_maximize',
    'nf nf-fa-window_minimize',
    'nf nf-fa-window_minimize',
    'nf nf-fa-window_restore',
    'nf nf-fa-window_restore',
    'nf nf-fa-windows',
    'nf nf-fa-wine_glass',
    'nf nf-fa-wolf_pack_battalion',
    'nf nf-fa-won_sign',
    'nf nf-fa-wordpress',
    'nf nf-fa-wordpress_simple',
    'nf nf-fa-wpbeginner',
    'nf nf-fa-wpexplorer',
    'nf nf-fa-wpforms',
    'nf nf-fa-wrench',
    'nf nf-fa-x_ray',
    'nf nf-fa-xbox',
    'nf nf-fa-xing',
    'nf nf-fa-xing_square',
    'nf nf-fa-y_combinator',
    'nf nf-fa-yahoo',
    'nf nf-fa-yandex',
    'nf nf-fa-yandex_international',
    'nf nf-fa-yelp',
    'nf nf-fa-yen_sign',
    'nf nf-fa-yoast',
    'nf nf-fa-youtube',
    'nf nf-fa-youtube_square'
  ],
  'mficons' => [
    [
      "txt" => "Applications and operating systems",
      "icons" => [
        "apache",
        "archlinux",
        "centos",
        "debian",
        "docker",
        "exherbo",
        "fedora",
        "freebsd",
        "gentoo",
        "gnome",
        "gradle",
        "jetty",
        "kde",
        "linux-mint",
        "maven",
        "netbsd",
        "nginx",
        "nginx-alt",
        "nginx-alt2",
        "osx",
        "raspberrypi",
        "redhat",
        "solaris",
        "suse",
        "tomcat",
        "ubuntu"
      ]
    ],[
      "txt" => "Brands",
      "icons" => [
        "aws",
        "dreamhost",
        "google",
        "google-alt",
        "google-code",
        "google-developers",
        "heroku",
        "wordpress"
      ]
    ], [
      "txt" => "Databases",
      "icons" => [
        "cassandra",
        "database",
        "database-alt",
        "database-alt2",
        "hadoop",
        "mariadb",
        "mongodb",
        "mssql",
        "mysql",
        "mysql-alt",
        "oracle",
        "oracle-alt",
        "postgres",
        "postgres-alt",
        "redis"
      ]
    ], [
      "txt" => "File types",
      "icons" => [
        "svg"
      ]
    ], [
      "txt" => "Frameworks",
      "icons" => [
        "grails",
        "grails-alt",
        "laravel",
        "phone-gap",
        "playframework",
        "playframework-alt",
        "plone",
        "ruby-on-rails",
        "ruby-on-rails-alt",
        "symfony"
      ]
    ], [
      "txt" => "Programming languages",
      "icons" => [
        "c",
        "clojure",
        "cplusplus",
        "csharp",
        "css",
        "elixir",
        "erlang",
        "haskell",
        "html",
        "java",
        "java-bold",
        "java-duke",
        "javascript",
        "javascript-alt",
        "nodejs",
        "objc",
        "perl",
        "php",
        "php-alt",
        "python",
        "ruby",
        "scala",
        "scala-alt",
        "script",
        "script-alt",
        "shell"
      ]
    ], [
      "txt" => "Miscellaneous (Deprecated)",
      "icons" => [
        "3dprint",
        "bomb",
        "coffee-bean",
        "fire-alt",
        "ghost",
        "line-graph",
        "looking",
        "microscope",
        "splatter"
      ]
    ], [
      "txt" => "Mobile",
      "icons" => [
        "antenna",
        "blackberry",
        "iphone",
        "mobile-device",
        "mobile-phone-alt",
        "mobile-phone-broadcast",
        "phone-alt",
        "phone-retro",
        "satellite",
        "wireless"
      ]
    ]
  ],
  "material" => [
    "menu",
    "caret-down",
    "download",
    "group",
    "rss",
    "shape",
    "spinner",
    "ungroup",
    "500px",
    "8tracks",
    "amazon",
    "blogger",
    "delicious",
    "disqus",
    "flattr",
    "flickr",
    "github-alt",
    "google-old",
    "linkedin",
    "odnoklassniki",
    "outlook",
    "paypal-alt",
    "pinterest",
    "playstation",
    "reddit",
    "skype",
    "slideshare",
    "soundcloud",
    "tumblr",
    "twitch",
    "vimeo",
    "whatsapp",
    "xbox",
    "yahoo",
    "youtube-play",
    "youtube",
    "google",
    "google-plus-box",
    "google-plus",
    "paypal",
    "3d-rotation",
    "airplane-off",
    "airplane",
    "album",
    "archive",
    "assignment-account",
    "assignment-alert",
    "assignment-check",
    "assignment-o",
    "assignment-return",
    "assignment-returned",
    "assignment",
    "attachment-alt",
    "attachment",
    "audio",
    "badge-check",
    "balance-wallet",
    "balance",
    "battery-alert",
    "battery-flash",
    "battery-unknown",
    "battery",
    "bike",
    "block-alt",
    "block",
    "boat",
    "book-image",
    "book",
    "bookmark-outline",
    "bookmark",
    "brush",
    "bug",
    "bus",
    "cake",
    "car-taxi",
    "car-wash",
    "car",
    "card-giftcard",
    "card-membership",
    "card-travel",
    "card",
    "case-check",
    "case-download",
    "case-play",
    "case",
    "cast-connected",
    "cast",
    "chart-donut",
    "chart",
    "city-alt",
    "city",
    "close-circle-o",
    "close-circle",
    "close",
    "cocktail",
    "code-setting",
    "code-smartphone",
    "code",
    "coffee",
    "collection-bookmark",
    "collection-case-play",
    "collection-folder-image",
    "collection-image-o",
    "collection-image",
    "collection-item-1",
    "collection-item-2",
    "collection-item-3",
    "collection-item-4",
    "collection-item-5",
    "collection-item-6",
    "collection-item-7",
    "collection-item-8",
    "collection-item-9-plus",
    "collection-item-9",
    "collection-item",
    "collection-music",
    "collection-pdf",
    "collection-plus",
    "collection-speaker",
    "collection-text",
    "collection-video",
    "compass",
    "cutlery",
    "delete",
    "dialpad",
    "dns",
    "drink",
    "edit",
    "email-open",
    "email",
    "eye-off",
    "eye",
    "eyedropper",
    "favorite-outline",
    "favorite",
    "filter-list",
    "fire",
    "flag",
    "flare",
    "flash-auto",
    "flash-off",
    "flash",
    "flip",
    "flower-alt",
    "flower",
    "font",
    "fullscreen-alt",
    "fullscreen-exit",
    "fullscreen",
    "functions",
    "gas-station",
    "gesture",
    "globe-alt",
    "globe-lock",
    "globe",
    "graduation-cap",
    "home",
    "hospital-alt",
    "hospital",
    "hotel",
    "hourglass-alt",
    "hourglass-outline",
    "hourglass",
    "http",
    "image-alt",
    "image-o",
    "image",
    "inbox",
    "invert-colors-off",
    "invert-colors",
    "key",
    "label-alt-outline",
    "label-alt",
    "label-heart",
    "label",
    "labels",
    "lamp",
    "landscape",
    "layers-off",
    "layers",
    "library",
    "link",
    "lock-open",
    "lock-outline",
    "lock",
    "mail-reply-all",
    "mail-reply",
    "mail-send",
    "mall",
    "map",
    "money-box",
    "money-off",
    "money",
    "more-vert",
    "more",
    "movie-alt",
    "movie",
    "nature-people",
    "nature",
    "navigation",
    "open-in-browser",
    "open-in-new",
    "palette",
    "parking",
    "pin-account",
    "pin-assistant",
    "pin-drop",
    "pin-help",
    "pin-off",
    "pin",
    "pizza",
    "plaster",
    "power-setting",
    "power",
    "print",
    "puzzle-piece",
    "quote",
    "railway",
    "receipt",
    "refresh-alt",
    "refresh-sync-alert",
    "refresh-sync-off",
    "refresh-sync",
    "refresh",
    "roller",
    "ruler",
    "scissors",
    "screen-rotation-lock",
    "screen-rotation",
    "search-for",
    "search-in-file",
    "search-in-page",
    "search-replace",
    "search",
    "seat",
    "settings-square",
    "settings",
    "shield-check",
    "shield-security",
    "shopping-basket",
    "shopping-cart-plus",
    "shopping-cart",
    "sign-in",
    "sort-amount-asc",
    "sort-amount-desc",
    "sort-asc",
    "sort-desc",
    "spellcheck",
    "storage",
    "store-24",
    "store",
    "subway",
    "sun",
    "tab-unselected",
    "tab",
    "tag-close",
    "tag-more",
    "tag",
    "thumb-down",
    "thumb-up-down",
    "thumb-up",
    "ticket-star",
    "toll",
    "toys",
    "traffic",
    "translate",
    "triangle-down",
    "triangle-up",
    "truck",
    "turning-sign",
    "wallpaper",
    "washing-machine",
    "window-maximize",
    "window-minimize",
    "window-restore",
    "wrench",
    "zoom-in",
    "zoom-out",
    "alert-circle-o",
    "alert-circle",
    "alert-octagon",
    "alert-polygon",
    "alert-triangle",
    "help-outline",
    "help",
    "info-outline",
    "info",
    "notifications-active",
    "notifications-add",
    "notifications-none",
    "notifications-off",
    "notifications-paused",
    "notifications",
    "account-add",
    "account-box-mail",
    "account-box-o",
    "account-box-phone",
    "account-box",
    "account-calendar",
    "account-circle",
    "account-o",
    "account",
    "accounts-add",
    "accounts-alt",
    "accounts-list-alt",
    "accounts-list",
    "accounts-outline",
    "accounts",
    "face",
    "female",
    "male-alt",
    "male-female",
    "male",
    "mood-bad",
    "mood",
    "run",
    "walk",
    "cloud-box",
    "cloud-circle",
    "cloud-done",
    "cloud-download",
    "cloud-off",
    "cloud-outline-alt",
    "cloud-outline",
    "cloud-upload",
    "cloud",
    "file-plus",
    "file-text",
    "file",
    "folder-outline",
    "folder-person",
    "folder-star-alt",
    "folder-star",
    "folder",
    "gif",
    "upload",
    "border-all",
    "border-bottom",
    "border-clear",
    "border-color",
    "border-horizontal",
    "border-inner",
    "border-left",
    "border-outer",
    "border-right",
    "border-style",
    "border-top",
    "border-vertical",
    "copy",
    "crop",
    "format-align-center",
    "format-align-justify",
    "format-align-left",
    "format-align-right",
    "format-bold",
    "format-clear-all",
    "format-clear",
    "format-color-fill",
    "format-color-reset",
    "format-color-text",
    "format-indent-decrease",
    "format-indent-increase",
    "format-italic",
    "format-line-spacing",
    "format-list-bulleted",
    "format-list-numbered",
    "format-ltr",
    "format-rtl",
    "format-size",
    "format-strikethrough-s",
    "format-strikethrough",
    "format-subject",
    "format-underlined",
    "format-valign-bottom",
    "format-valign-center",
    "format-valign-top",
    "redo",
    "select-all",
    "space-bar",
    "text-format",
    "transform",
    "undo",
    "wrap-text",
    "comment-alert",
    "comment-alt-text",
    "comment-alt",
    "comment-edit",
    "comment-image",
    "comment-list",
    "comment-more",
    "comment-outline",
    "comment-text-alt",
    "comment-text",
    "comment-video",
    "comment",
    "comments",
    "check-all",
    "check-circle-u",
    "check-circle",
    "check-square",
    "check",
    "circle-o",
    "circle",
    "dot-circle-alt",
    "dot-circle",
    "minus-circle-outline",
    "minus-circle",
    "minus-square",
    "minus",
    "plus-circle-o-duplicate",
    "plus-circle-o",
    "plus-circle",
    "plus-square",
    "plus",
    "square-o",
    "star-circle",
    "star-half",
    "star-outline",
    "star",
    "bluetooth-connected",
    "bluetooth-off",
    "bluetooth-search",
    "bluetooth-setting",
    "bluetooth",
    "camera-add",
    "camera-alt",
    "camera-bw",
    "camera-front",
    "camera-mic",
    "camera-party-mode",
    "camera-rear",
    "camera-roll",
    "camera-switch",
    "camera",
    "card-alert",
    "card-off",
    "card-sd",
    "card-sim",
    "desktop-mac",
    "desktop-windows",
    "device-hub",
    "devices-off",
    "devices",
    "dock",
    "floppy",
    "gamepad",
    "gps-dot",
    "gps-off",
    "gps",
    "headset-mic",
    "headset",
    "input-antenna",
    "input-composite",
    "input-hdmi",
    "input-power",
    "input-svideo",
    "keyboard-hide",
    "keyboard",
    "laptop-chromebook",
    "laptop-mac",
    "laptop",
    "mic-off",
    "mic-outline",
    "mic-setting",
    "mic",
    "mouse",
    "network-alert",
    "network-locked",
    "network-off",
    "network-outline",
    "network-setting",
    "network",
    "phone-bluetooth",
    "phone-end",
    "phone-forwarded",
    "phone-in-talk",
    "phone-locked",
    "phone-missed",
    "phone-msg",
    "phone-paused",
    "phone-ring",
    "phone-setting",
    "phone-sip",
    "phone",
    "portable-wifi-changes",
    "portable-wifi-off",
    "portable-wifi",
    "radio",
    "reader",
    "remote-control-alt",
    "remote-control",
    "router",
    "scanner",
    "smartphone-android",
    "smartphone-download",
    "smartphone-erase",
    "smartphone-info",
    "smartphone-iphone",
    "smartphone-landscape-lock",
    "smartphone-landscape",
    "smartphone-lock",
    "smartphone-portrait-lock",
    "smartphone-ring",
    "smartphone-setting",
    "smartphone-setup",
    "smartphone",
    "speaker",
    "tablet-android",
    "tablet-mac",
    "tablet",
    "tv-alt-play",
    "tv-list",
    "tv-play",
    "tv",
    "usb",
    "videocam-off",
    "videocam-switch",
    "videocam",
    "watch",
    "wifi-alt-2",
    "wifi-alt",
    "wifi-info",
    "wifi-lock",
    "wifi-off",
    "wifi-outline",
    "wifi",
    "arrow-left-bottom",
    "arrow-left",
    "arrow-merge",
    "arrow-missed",
    "arrow-right-top",
    "arrow-right",
    "arrow-split",
    "arrows",
    "caret-down-circle",
    "caret-left-circle",
    "caret-left",
    "caret-right-circle",
    "caret-right",
    "caret-up-circle",
    "caret-up",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "forward",
    "long-arrow-down",
    "long-arrow-left",
    "long-arrow-return",
    "long-arrow-right",
    "long-arrow-tab",
    "long-arrow-up",
    "rotate-ccw",
    "rotate-cw",
    "rotate-left",
    "rotate-right",
    "square-down",
    "square-right",
    "swap-alt",
    "swap-vertical-circle",
    "swap-vertical",
    "swap",
    "trending-down",
    "trending-flat",
    "trending-up",
    "unfold-less",
    "unfold-more",
    "directions-bike",
    "directions-boat",
    "directions-bus",
    "directions-car",
    "directions-railway",
    "directions-run",
    "directions-subway",
    "directions-walk",
    "directions",
    "local-activity",
    "local-airport",
    "local-atm",
    "local-bar",
    "local-cafe",
    "local-car-wash",
    "local-convenience-store",
    "local-dining",
    "local-drink",
    "local-florist",
    "local-gas-station",
    "local-grocery-store",
    "local-hospital",
    "local-hotel",
    "local-laundry-service",
    "local-library",
    "local-mall",
    "local-movies",
    "local-offer",
    "local-parking",
    "local-pharmacy",
    "local-phone",
    "local-pizza",
    "local-post-office",
    "local-printshop",
    "local-see",
    "local-shipping",
    "local-store",
    "local-taxi",
    "local-wc",
    "my-location",
    "apps",
    "grid-off",
    "grid",
    "view-agenda",
    "view-array",
    "view-carousel",
    "view-column",
    "view-comfy",
    "view-compact",
    "view-dashboard",
    "view-day",
    "view-headline",
    "view-list-alt",
    "view-list",
    "view-module",
    "view-quilt",
    "view-stream",
    "view-subtitles",
    "view-toc",
    "view-web",
    "view-week",
    "widgets",
    "alarm-check",
    "alarm-off",
    "alarm-plus",
    "alarm-snooze",
    "alarm",
    "calendar-alt",
    "calendar-check",
    "calendar-close",
    "calendar-note",
    "calendar",
    "time-countdown",
    "time-interval",
    "time-restore-setting",
    "time-restore",
    "time",
    "timer-off",
    "timer",
    "android-alt",
    "android",
    "apple",
    "behance",
    "codepen",
    "dribbble",
    "dropbox",
    "evernote",
    "facebook-box",
    "facebook",
    "github-box",
    "github",
    "google-drive",
    "google-earth",
    "google-glass",
    "google-maps",
    "google-pages",
    "google-play",
    "instagram",
    "language-css3",
    "language-html5",
    "language-javascript",
    "language-python-alt",
    "language-python",
    "lastfm",
    "linkedin-box",
    "pinterest-box",
    "pocket",
    "polymer",
    "share",
    "stackoverflow",
    "steam-square",
    "steam",
    "twitter-box",
    "twitter",
    "vk",
    "wikipedia",
    "windows",
    "aspect-ratio-alt",
    "aspect-ratio",
    "blur-circular",
    "blur-linear",
    "blur-off",
    "blur",
    "brightness-2",
    "brightness-3",
    "brightness-4",
    "brightness-5",
    "brightness-6",
    "brightness-7",
    "brightness-auto",
    "brightness-setting",
    "broken-image",
    "center-focus-strong",
    "center-focus-weak",
    "compare",
    "crop-16-9",
    "crop-3-2",
    "crop-5-4",
    "crop-7-5",
    "crop-din",
    "crop-free",
    "crop-landscape",
    "crop-portrait",
    "crop-square",
    "exposure-alt",
    "exposure",
    "filter-b-and-w",
    "filter-center-focus",
    "filter-frames",
    "filter-tilt-shift",
    "gradient",
    "grain",
    "graphic-eq",
    "hdr-off",
    "hdr-strong",
    "hdr-weak",
    "hdr",
    "iridescent",
    "leak-off",
    "leak",
    "looks",
    "loupe",
    "panorama-horizontal",
    "panorama-vertical",
    "panorama-wide-angle",
    "photo-size-select-large",
    "photo-size-select-small",
    "picture-in-picture",
    "slideshow",
    "texture",
    "tonality",
    "vignette",
    "wb-auto",
    "eject-alt",
    "eject",
    "equalizer",
    "fast-forward",
    "fast-rewind",
    "forward-10",
    "forward-30",
    "forward-5",
    "hearing",
    "pause-circle-outline",
    "pause-circle",
    "pause",
    "play-circle-outline",
    "play-circle",
    "play",
    "playlist-audio",
    "playlist-plus",
    "repeat-one",
    "repeat",
    "replay-10",
    "replay-30",
    "replay-5",
    "replay",
    "shuffle",
    "skip-next",
    "skip-previous",
    "stop",
    "surround-sound",
    "tune",
    "volume-down",
    "volume-mute",
    "volume-off",
    "volume-up",
    "n-1-square",
    "n-2-square",
    "n-3-square",
    "n-4-square",
    "n-5-square",
    "n-6-square",
    "neg-1",
    "neg-2",
    "plus-1",
    "plus-2",
    "sec-10",
    "sec-3",
    "zero",
    "airline-seat-flat-angled",
    "airline-seat-flat",
    "airline-seat-individual-suite",
    "airline-seat-legroom-extra",
    "airline-seat-legroom-normal",
    "airline-seat-legroom-reduced",
    "airline-seat-recline-extra",
    "airline-seat-recline-normal",
    "airplay",
    "closed-caption",
    "confirmation-number",
    "developer-board",
    "disc-full",
    "explicit",
    "flight-land",
    "flight-takeoff",
    "flip-to-back",
    "flip-to-front",
    "group-work",
    "hd",
    "hq",
    "markunread-mailbox",
    "memory",
    "nfc",
    "play-for-work",
    "power-input",
    "present-to-all",
    "satellite",
    "tap-and-play",
    "vibration",
    "voicemail",
    "brightness-high"
  ]
];
$res['total'] = count($res['faicons']) + count($res['material']);
foreach ( $res['mficons'] as $m ){
  $res['total'] += count($m['icons']);
}
return $res;